### ISSUE TITLE
Affichage région et département

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#22]
Intitulé

    En tant qu’utilisateur
    Je veux que l'affichage des dalles soient dynamiques selon le zoom
    Afin d'avoir une navigation fluide

Spécifications

    À grande échelle, les dalles sont découpées en bloc selon les régions / département
    

Critères d'acceptation

Le ticket est terminé lorsque :

    Lorsque au changement de zoom, les dalles s'affichent suivant les spécifications demandées.

**Comment by TerryMoreauIGN** [comment]
Fonctionnalité intéressante à garder pour la future interface GPF !
