### ISSUE TITLE
Bloqué le niveau de zoom max

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#37]
Lorsque que l'on zoome au max, une erreur apparait.

Solution de contournement : ne pas zoomer trop

Solution à apporter bloqué le zoom de la carte à max 10 -12

**Comment by loux22** [comment]
j'ai mis 16

**Comment by TerryMoreauIGN** [comment]
C'est une bonne idée le bloquage, bien joué ! 16 me convient perso.
