### ISSUE TITLE
Affichage des produits dérivée

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#44]
Intitulé

    En tant qu’utilisateur
    Je veux pouvoir connaitre les produits dérivés disponibles, 
    afin de faire ma sélection
    

Spécifications

    Une flèche au niveau de la dalle permet d'afficher aux cliques les produits dérivées associées. La liste des produits dérivées est accompagnée d'un bouton de téléchargement.
    
    

Critères d'acceptation

    Je peux connaitre les produits dérivés de chacune de mes dalles.

**Comment by TerryMoreauIGN** [comment]
Tu parles du texte "Produits dérivés" dans le bandeau de droite ?

**Comment by TerryMoreauIGN** [comment]
Si oui, c'est okay pour moi

**Comment by mmohadIGN** [comment]
Oui donc on laisse comme ça ?
