### ISSUE TITLE
Montée en compétence sur le catalogue geonetwork

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#45]
Intitulé

    En tant que dev
    Je veux pouvoir utiliser l'api geo-network, 
    afin de m'en servir dans mes prochains dev
    

Spécifications

    lien des docs et ect: 

https://csw.geopf.fr/geonetwork/srv/fre/csw?REQUEST=GetCapabilities&VERSION=2.0.2&SERVICE=CSW

https://data.geopf.fr/csw?REQUEST=GetCapabilities&VERSION=2.0.2&SERVICE=CSW

https://geonetwork-opensource.org/manuals/4.0.x/fr/api/the-geonetwork-api.html

    

Critères d'acceptation

    Je peux me servir du catalogue de metadata

**Comment by mmohadIGN** [comment]
En cour de demande des accés à Mirela

**Comment by TerryMoreauIGN** [comment]
Cette montée en compétence doit être faite dans le cadre du projet catalogue, donc on clôt ce ticket.
