### ISSUE TITLE
Montée en charge

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#64]
Intitulé

    En tant que développeur
    Je veux tester la montée en chargé
    Afin de pouvoir voir m'assurer que mon site est résiliant

Spécifications

    Je lance un bench de 60 sur le site en qualif 

Critères d'acceptation

Le ticket est terminé lorsque

    Le site fonctionne à pus de 60.

Commentaires:

**Comment by TerryMoreauIGN** [comment]
A voir une fois l'utilisation par le site du flux WFS pour la liste des dalles et des blocs (vu avec Valentin).
