### ISSUE TITLE
Tour guide ? explication Téléchargement

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#66]
## Intitulé

* En tant qu'utilisateur
* Je veux un tutoriel
* Afin de comprendre comment fonctionne le téléchargement

 ## Spécifications

    Première connexion, j'ai un fond grisé avec un mot "bienvenue sur la nouvelle interface d'accès aux produits LiDAR HD".
    Ensuite, flèche vers la cartographie avec explication : "les zones entourées de bleu sont les zones où les nuages de points classés       sont disponibles, cliquez à l'endroit souhaité et l'outil vous y conduit automatiquement."
    Ensuite, flèche vers le bandeau de droite "ce bandeau vous permet de saisir des dalles (au clic, en dessinant une figure ou en important un fichier cartographique GeoJSON) et d'en retrouver la liste pour les télécharger ou les visualiser. Vous y retrouverez les dalles de chaque polygone (+flèche vers le bouton liste de polygone), et la liste de l'ensemble des dalles sélectionnées, tous polygones confondus (+flèche vers le bouton liste des dalles intersectées)."
    Ensuite, flèche vers le bouton "que faire de la liste txt?" : "ce bouton d'aide vous permet de comprendre comment télécharger les dalles sélectionnées à partir d'un plugin web de téléchargement massif".

## Critères d'acceptation

    
- [ ] Un mot de bienvenue est affiché à la première connexion et le tour guide est enclenché
- [ ] Les textes spécifiés sont affichés aux bons endroits

## Commentaires

**Comment by mmohadIGN** [comment]
@TerryMoreauIGN Est-ce que tu peux écrire le contenu des tutos ? pour rappel l'url : https://ant.design/components/tour

**Comment by TerryMoreauIGN** [comment]
Tu peux choisir l'outil que tu veux pour les tutos de bienvenue. 
Ce que je veux exactement : 
Première connexion, j'ai un fond grisé avec un mot "bienvenue sur la nouvelle interface d'accès aux produits LiDAR HD". 
Ensuite, petite flèche vers la cartographie avec explication : "les zones entourées de bleu sont les zones où les nuages de points classés sont disponibles, cliquez à l'endroit souhaité et l'outil vous y conduit automatiquement."

**Comment by TerryMoreauIGN** [comment]
A mettre dans le lot de la future interface intégrant la GPF (un peu trop tard à implémenter) -> Vu avec Valentin.
