### ISSUE TITLE
Zoom sur une dalle en particulier

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#68]
Quand je cherche à trouver la localisation d'une dalle après saisie de l'emprise, le zoom est trop loin pour pouvoir la différencier des dalles voisines -> prévoir un niveau de zoom plus important sur la dalle

**Comment by TerryMoreauIGN** [comment]
remarque : avoir la continuité de la surbrillance de la dalle (ici en jaune) sur les boutons "localisation" et "suppression".
