### ISSUE TITLE
Ajouter texte d'information pour télécharger les dalles dans le fichier txt

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#71]
Après avoir cliquer sur le bouton "que faire avec cette liste?", une pop-up s'affiche : 
" Vous souhaitez télécharger les dalles sélectionnées :
1) Vous n'avez pas encore installé de plugin web de téléchargement massif comme [downthemall](https://www.downthemall.net/) : installez-le, c'est rapide et libre ! 
2) Vous avez installé un plugin web de téléchargement massif : 
- téléchargement directement via l'interface : cliquer sur le polygone en question (ou bien sur le bouton "liste des nuages de points classés") pour afficher les dalles. Cliquer-droit sur une dalle au hasard, choisir "downthemall" et lancer le téléchargement à partir de l'interface qui vient de s'ouvrir.
-  téléchargement via le fichier texte : retrouver dans vos "téléchargements" la liste des URL des dalles intersectées par la figure saisie ou importée. Glisser-déposer le fichier sur votre navigateur : un onglet s'ouvre avec la liste des URL. Cliquer-droit et choisir "downthemall". L'interface de gestion des téléchargements s'ouvre. Lancer le téléchargement massif."

**Comment by TerryMoreauIGN** [comment]
A reprendre en modale : 
- faire une première partie indiquant l'utilisation d'un logiciel et proposant les deux exemples de plug-in web ;
- insérer la vidéo (ou le lien) à la suite (+ texte à ajouter pour l'introduire) ;

**Comment by mmohadIGN** [comment]
Il me faudrait le lien de la vidéo et le nom des deux plug-ins retenu.

**Comment by TerryMoreauIGN** [comment]
Lien vers la vidéo : https://www.youtube.com/watch?time_continue=4&v=-YomQJC6S38&embeds_referring_euri=https%3A%2F%2Fgeoservices.ign.fr%2F&source_ve_path=MjM4NTE&feature=emb_title

Les deux plugin : 
• Xtreme Download Manager : https://xtremedownloadmanager.com/
• DownThemAll! : https://www.downthemall.net/
