### ISSUE TITLE
Changement de l'affichage des blocs

### ISSUE THREAD

**Issue by mmohadIGN** [ignf-sidc/diffusion_lidar#74]
A l'affichage grande échelle, est-il possible de fusionner les blocs comme une seule et même surface ? (évidemment quand un bloc n'a pas de voisin, ca reste un bloc). Remarque : le clic sur la surface fusionnée propose la même fonction de zoom, à l'endroit cliqué.

**Comment by TerryMoreauIGN** [comment]
Idealement fusionner tous les blocs en une seule couche indiquant la disponibilité.
