### ISSUE TITLE
Listing des noms des programmes qui n'ont pas d'entête 

### ISSUE THREAD

**Issue by fbacquelot** [ignf-sidc/diffusion_lidar#92]
* Projet **diffusion_lidar** :
* dans le dossier **backend** : 
- [ ] **Dockerfile** => aucune entête fournie;
- [ ] **docker-entrypoint.sh** => aucune entête fournie;

* dans le sous-dossier **api/app/adapters**: 
- [ ] **ExtractDataFile.py** => pas d'entête;

* dans le sous-dossier **api/app/routes**:
- [ ] **test.py** => pas d'entête fournie;
- [ ] **upload.py** => pas d'entête fournie;

* dans le sous-dossier **docker/prod/api**:
- [ ] **Dockerfile** => pas d'entête fournie;

* dans le sous-dossier **docker/prod/frontend**:
- [ ] **Dockerfile** => pas d'entête fournie;

* dans le sous-dossier **frontend**:
- [ ] **Dockerfile** => pas d'entête fournie;

* dans le sous-dossier **frontend/src** :
- [ ] tous les fichiers écrits en javascript, ce sont : 
- [ ] **App.js**, 
- [ ] **App.test.js**, 
- [ ] **index.js**, 
- [ ] **registerServiceWorker.js**, 
- [ ] **reportWebVitals.js**, 
- [ ] **setupTests.js**

* dans le sous-dossier **frontend/src/component** :
- [ ] **MapWrapper.jsx** => aucune entête fournie.

**Comment by vsasyan-ignf** [comment]
non applicable pour les sites web
