### ISSUE TITLE
Mettre à jour le nom des couches du service WMS

### ISSUE THREAD

**Issue by vsasyan-ignf** [ignf-sidc/diffusion_lidar#96]
Couches listant les blocs et les dalles du flux WMS avec les noms définitifs sont disponibles.

Voici le changement à faire :

* `ta_lidar-hd:dalle` => `IGNF_LIDAR-HD_TA:nuage-dalle`
* `ta_lidar-hd:bloc` => `IGNF_LIDAR-HD_TA:nuage-bloc`

Les anciennes couches seront désactivées d'ici 2-3 mois.

**Comment by mmohadIGN** [comment]
Est-ce que la modif est aussi à prévoir pour diffuisonMNX @vsasyan-ignf

**Comment by vsasyan-ignf** [comment]
> Est-ce que la modif est aussi à prévoir pour diffuisonMNX @vsasyan-ignf

Normalement sur l'autre interface tu n'utilise pas ces couches, mais les nouvelles qui ont déjà le bon nom. Sauf erreur de ma part.

en tout cas c'est ok pour ce site.
